# Generated by Django 5.0.4 on 2024-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('f_estreno', models.DateField()),
                ('trailer', models.URLField()),
                ('poster', models.URLField()),
                ('director', models.CharField(max_length=50)),
                ('protagonistas', models.CharField(max_length=100)),
            ],
        ),
    ]
