# Generated by Django 5.0.4 on 2024-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_ventaPeliculas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelicula",
            name="price",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
